name: Gradle Build
  
on: [push]

jobs:
         
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: |
          mkdir /opt/dependencies
          chmod +x /opt/dependencies
          ./gradlew --project-cache-dir /opt/dependencies build --info
         
        #uses: gradle/gradle-build-action@v2
       # with:
         # arguments: build
         
      - name: Copy downloaded jars
        run: |
          ls -al /opt/dependencies/
          find /opt/dependencies/ -name '*.jar'
       #  mkdir /opt/dependencies
       #  chmod 777 /home/runner/.gradle/.tmp/*
       #  ls -al /home/runner/.gradle/.tmp/
       #  cp -a /home/runner/.gradle/.tmp/. /opt/dependencies/
         
               
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'ProjectAction'
          path: '/opt/dependencies'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
           
