name: Dependency Checker
  
on: [push]

jobs:
         
  depchecktest:
    runs-on: windows-latest
    name: OVAS Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
                     
      - name: Download and Execute Dependency Checker
        shell: cmd
        run: |
          git clone https://github.com/babithalog/DependencyCheck.git
          cd DependencyCheck/DependencyCheck/bin
          icacls "./dependency-check.bat" /grant Users:F
          dir
         # chmod +x ./dependency-check.sh
          #ls -al         
          #./dependency-check.sh --project "Test" --scan "/home/runner/.gradle/caches/" -format "HTML" --out "/home/runner/reports"
        
        #  mkdir /home/runner/downloads
        #  curl "https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.0/dependency-check-7.0.0-release.zip" --output /home/runner/downloads/dependency-check-7.0.0-release.zip
          #curl "https://github.com/babithalog/Java/main/Tools/dependency-check-7.0.0-release.zip?raw=true" --output /home/runner/downloads/dependency-check-7.0.0-release.zip
        #  cd /home/runner/downloads
        #  ls -al
        #  chmod +x dependency-check-7.0.0-release.zip
        #  jar xvf dependency-check-7.0.0-release.zip
        #  ls -al
          
          
     # - name: Dependency Checker
      #  run: |
       #   chmod +x ./dependency-check/bin/dependency-check.sh
        #  ./dependency-check/bin/dependency-check.sh --project "Test" --scan "/home/runner/.gradle/caches/" -format "HTML" --out "/home/runner/reports"
            
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: /home/runner/reports
           
