name: Dependency Checker
  
on: [push]

jobs:
         
  depchecktest:
    runs-on: ubuntu-latest
    name: OVAS Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
     # - name: Change wrapper permissions
      #  run: chmod +x ./gradlew
        
     # - name: Build with Gradle
      #  run: ./gradlew build --info
                 
      - name: Download Dependency Checker
        run: |
          mkdir /home/runner/downloads
          curl "https://github.com/babithalog/Java/main/Tools/dependency-check-7.0.0-release.zip?raw=true" --output /home/runner/downloads/dependency-check.zip
          cd /home/runner/downloads
          ls -al
         # unzip dependency-check-7.0.0-release.zip
          
          
     # - name: Dependency Checker
      #  run: |
       #   chmod +x ./dependency-check/bin/dependency-check.sh
        #  ./dependency-check/bin/dependency-check.sh --project "Test" --scan "/home/runner/.gradle/caches/" -format "HTML" --out "/home/runner/reports"
            
    #  - name: Upload Test results
     #   uses: actions/upload-artifact@master
      #  with:
       #    name: Depcheck report
        #   path: /home/runner/reports
           
