name: Dependency Checker
  
on: [push]

jobs:
         
  depchecktest:
    runs-on: ubuntu-latest
    name: OVAS Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build --info
                 
      - name: Copy downloaded jars
        run: |
          find /home/runner/.gradle/caches/ -name "*.jar" -print0 | xargs -0 cp -t "./"
          find ./ -name "*.jar"
     
      - name: Dependency Checker
        run: |
          chmod +x ./dependency-check/bin/dependency-check.sh
          ./dependency-check/bin/dependency-check.sh --project "Test" --scan "/home/runner/.gradle/caches/" -format "HTML" --out "/home/runner/reports"
            
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: /home/runner/reports
           
