name: Gradle Build
  
on: [push]

jobs:
         
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build --info
                 
      - name: Copy downloaded jars
        run: |
         # mkdir /home/runner/dependencies
         # chmod 777 /home/runner/dependencies
          find /home/runner/.gradle/caches/ -name "*.jar" -print0 | xargs -0 cp -t "./"
          find ./ -name "*.jar"
         # find /home/runner/dependencies -name "*.jar"
                       
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'ProjectAction'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 0
            --enableRetired
            #--scan '/home/runner/dependencies'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
           
