name: Gradle Build
  
on: [push]

jobs:
         
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/.tmp           
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle/.tmp/*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --info
        #uses: gradle/gradle-build-action@v2
       # with:
         # arguments: build
         
               
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'ProjectAction'
          path: '/home/runner/.gradle/'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
           
