name: Download artifact
on:
  workflow_run:
    workflows: ["OVAS Scan"]
    types: 
      - completed


#GITHUB_TOKEN permissions (required)
permissions: 
  contents: read
  
jobs:
         
  ovas-scan:
    runs-on: self-hosted
    name: Download Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: Depcheck report
    
      - name: Display structure of downloaded files
        run: ls -R
